version: '3'

services:
  my_sql_8:
    image: mysql:8.0.18
    environment:
      MYSQL_ROOT_PASSWORD: 'test_pass'
      MYSQL_DATABASE: "db8"
    volumes:
      - ./volumes/mysql8:/var/lib/mysql
    ports:
      - "3308:3306"

  my_sql_5:
    image: mysql:5.7.25
    environment:
      MYSQL_ROOT_PASSWORD: 'test_pass'
      MYSQL_DATABASE: "db5"
    volumes:
      - ./volumes/mysql5:/var/lib/mysql
    ports:
      - "3305:3306"